# SPDX-FileCopyrightText: Josef Andersson
#
# SPDX-License-Identifier: CC0-1.0

---
name: Changelog-Tag Workflow

on:
  push:
    branches:
      - main
    tags:
      - v[0-9]+.[0-9]+.[0-9]+
  pull_request:
    branches:
      - main

jobs:
  dco:
    uses: ./.github/workflows/dco.yml
  license:
    uses: ./.github/workflows/license.yml
  lint:
    uses: ./.github/workflows/lint.yml
  coverage:
    uses: ./.github/workflows/coverage.yml
  test:
    needs: [license, lint, coverage]
    uses: ./.github/workflows/test.yml
  snapbuild:
    needs: [test]
    uses: ./.github/workflows/snapbuild.yml
